spring.application.name=Day_16_07_26_springboot

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# MySQL
spring.datasource.url=jdbc:mysql://${MYSQL_HOST:localhost}:3307/bookdb
spring.datasource.username=root
spring.datasource.password=root

server.port=8080

spring.profiles.active=Prod

# Actuator
management.endpoints.web.exposure.include=*
management.endpoints.web.base-path=/actuator

# Logging
logging.level.root=INFO
logging.level.com.coforge=DEBUG

logging.file.name=log/app.log

logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} %-5level {%thread} %logger{36} -%msg%n
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} %-5level {%thread} %logger{36} -%msg%n